# general settings
name: train_VIFusion
model_type: VIFusion
phase: train
num_gpu: 1
manual_seed: 3407


# dataset and data loader settings
datasets:
  train:
    name: train
    type: VI_FusionDataset
    crop_size: 768
    ir_path: './data/M3FD/ir/'
    vi_path: './data/M3FD/vi/'
    is_crop: True
    target_size: [1024,768]
    batch_size_per_gpu: 4
    num_worker_per_gpu: 8
    pin_memory: True
    data_len: -1

  val:
    # Please modify accordingly to use your own validation
    # Or comment the val block if do not need validation during training
    name: val
    type: VI_FusionDataset
    crop_size: 768
    ir_path: './data/M3FD_test/ir/'
    vi_path: './data/M3FD_test/vi/'
    is_crop: True
    target_size: [1024,768]
    batch_size_per_gpu: 16
    num_worker_per_gpu: 8
    pin_memory: True
    data_len: -1


# network structures
network_Encoder:
  type: Shared_Encoder_Fusion
  in_channels: 16

network_Fusion:
  type: Fusion_Decoder_Fusion
  in_channels: 16
  out_channel: 1

path:
  # pretrain_network_VIFusionYOLO: /home/gyy/IRFusion-main/PTH/VI_M3FD.pth
  pretrain_network_VIFusion: ~
  training_states:
  strict_load_g: true
  resume_state: ~

# training settings
train:
  alpha: 0.09
  loss_dict: [20000, 30000]
  #n_epoch: 300
  optimizer_encoder:
    type: Adam
    lr: !!float 2e-4

  optimizer_fusion:
    type: Adam
    lr: !!float 2e-4

  scheduler:
    type: MultiStepLR
    milestones: [10000, 50000, 100000]
    gamma: 0.5

  total_iter: 300000
  warmup_iter: -1  # -1 no warm up

  #Loss
  Loss:
    type: Fusionloss_VI
    device: cuda

val:
  pbar: true
  data_dir: './data/M3FD_test/'
  name: 'M3FD_test'
  start_val: 0
  val_freq: !!float 500
  save_img: true
  save_img_y: false

  metrics:
    EN: 
      type: ~
    SF: 
      type: ~
    AG: 
      type: ~
    SD: 
      type: ~
    CC: 
      type: ~
    SCD: 
      type: ~
    MSE: 
      type: ~
      better: lower
    PSNR: 
      type: ~
    Qabf: 
      type: ~
    Nabf: 
      type: ~
      better: lower


# logging settings
logger:
  print_freq: 50
  only_save_log: true
  start_save: 0
  save_checkpoint_freq: !!float 1000
  only_save_last_best: true
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
